cadena = input("Introduce una cadena: ")
print("La cadena introducida es: ", cadena)
print("La cadena en mayúsculas es: ", cadena.upper())
print("La cadena en minúsculas es: ", cadena.lower())
print("La cadena en mayúsculas y minúsculas es: ", cadena.swapcase())
print(type(cadena))
numeroInt = int(input("Introduce un número: "))
print("El número introducido es: ", numeroInt)
print(type(numeroInt))
numeroFloat = float(input("Introduce un número: "))
print("El número introducido es: ", numeroFloat)
print(type(numeroFloat))